version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "voicefoundry-project"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1k7vmbl2lt61g"
s3_prefix = "voicefoundry-project"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
